# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Braintube-Micro"
license = "MIT"
licenselink = "https://github.com/mcg/braintube-microblog-theme/blob/master/LICENSE"
description = "A customized port of the Ghost arabica theme for Hugo"
homepage = "https://github.com/mcg/braintube-microblog-theme/"
tags = ["blog", "minimal"]
features = ["smooth", "minimal"]
min_version = "0.41"

[author]
  name = "Matthew Gregg"
  homepage = "https://braintube.com

# If porting an existing theme
[original]
  name = "Musings"
  homepage = "https://www.amitgawande.com"
  repo = "https://github.com/am1t/musings"
